networks:
    NetDocker:    
  
services:
  restAPI:
    build:
         context: .
         dockerfile: NetDocker.API/Dockerfile
    ports:
       - 8003:1433
    networks:
        - NetDocker


  appdatabase:
    container_name: app-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
       - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=DevTest123
    networks:
        - NetDocker

  netdockerwebapp:
    container_name: web-blazor-app
    image: ${DOCKER_REGISTRY-}netdockerwebapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 8001:8080
    depends_on:
       - appdatabase
    environment:
        - DB_HOST=appdatabase
        - DB_NAME=BlazerServerSideTest
        - DB_SA_PASSWORD=DevTest123
        - ASPNETCORE_Kestrel__Certificates__Default__Password=DEVPW
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
        - NetDocker
